version: "3.8"
services:
  wiki:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_CONNECTION_STRING: "postgresql://wiki:KcZ9.VWrG>;eiU/G@db/wiki"
    command: /app/wiki --host=0.0.0.0

  db:
    image: postgres:14.0-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: wiki
      POSTGRES_PASSWORD: "KcZ9.VWrG>;eiU/G"
      POSTGRES_DB: wiki
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
